### ISSUE TITLE
module diffusers has no attribute ConsisIDTransformer3DModel

### ISSUE THREAD

**Issue by rolendyen** [PKU-YuanGroup/ConsisID#22]
"C:\Users\user\Downloads\ConsisID-241204\ConsisID\.glut\lib\site-packages\diffusers\utils\import_utils.py", line 846, in __getattr__
    raise AttributeError(f"module {self.__name__} has no attribute {name}")
AttributeError: module diffusers has no attribute ConsisIDTransformer3DModel. Did you mean: 'CogVideoXTransformer3DModel'?

why i meet the error ?

**Comment by SHYuanBest** [comment]
We have update [requirements.txt](https://github.com/PKU-YuanGroup/ConsisID/blob/main/requirements.txt), please reinstall the env. Or you can try `pip install git+https://github.com/SHYuanBest/ConsisID_diffusers.git`.

**Comment by DerThore** [comment]
Reinstalled it 5 times but still the same issue with diffusers. The requirements.txt seems to download an old version every time. pip install -r requirements.txt (with manually modified) did not work. After copy the new requirements, deleting env and install again, another error occures in egg_info (xformers) or when breaking install, modify requirements and then go on installing:
Collecting xformers==0.0.28.post3
  Using cached xformers-0.0.28.post3.tar.gz (7.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\pinokio\cache\TMPDIR\pip-install-mbfaevci\xformers_3c08cc2b69c74cd1bc0951c543e00ad6\setup.py", line 679, in <module>
          extensions, extensions_metadata = get_extensions()
        File "C:\pinokio\cache\TMPDIR\pip-install-mbfaevci\xformers_3c08cc2b69c74cd1bc0951c543e00ad6\setup.py", line 445, in get_extensions
          cuda_version = get_cuda_version(CUDA_HOME)
        File "C:\pinokio\cache\TMPDIR\pip-install-mbfaevci\xformers_3c08cc2b69c74cd1bc0951c543e00ad6\setup.py", line 133, in get_cuda_version
          raw_output = subprocess.check_output([nvcc_bin, "-V"], universal_newlines=True)
        File "C:\pinokio\bin\miniconda\lib\subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\pinokio\bin\miniconda\lib\subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\pinokio\bin\miniconda\lib\subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\pinokio\bin\miniconda\lib\subprocess.py", line 1456, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by SHYuanBest** [comment]
This may be a question about `xformers`, I can run it normally on` Linux`, `Windows` may need to refer to [here](https://github.com/facebookresearch/xformers?tab=readme-ov-file#installing-xformers) for installation. Or you can skip to install `xformers`, it should work fine, but slower.
https://github.com/facebookresearch/xformers?tab=readme-ov-file#installing-xformers

**Comment by DerThore** [comment]
Would not solve the issue with the ancient requirements.txt, which is keeping downloading. Skipping xformers brings the diffuser problem again.

**Comment by SHYuanBest** [comment]
> "C:\Users\user\Downloads\ConsisID-241204\ConsisID.glut\lib\site-packages\diffusers\utils\import_utils.py", line 846, in **getattr** raise AttributeError(f"module {self.**name**} has no attribute {name}") AttributeError: module diffusers has no attribute ConsisIDTransformer3DModel. Did you mean: 'CogVideoXTransformer3DModel'?
> 
> why i meet the error ?

still this error?

**Comment by SHYuanBest** [comment]
have you successfully install `pip install git+https://github.com/SHYuanBest/ConsisID_diffusers.git`?

**Comment by DerThore** [comment]
After installing it, a new error occures: Cannot find module moviepy

**Comment by SHYuanBest** [comment]
`pip install moviepy==2.1.1`

**Comment by DerThore** [comment]
Needed to install insidefaces==0.7.3, onnxruntime-gpu==1.19.2, facexlib==0.3.0, spandrel==0.4.0 and now it looks for skvideo which is not in the requirements, and trying to install that fails with "cannot find a suitable module"

**Comment by SHYuanBest** [comment]
It looks like the package in [requirements.txt](https://github.com/PKU-YuanGroup/ConsisID/blob/main/requirements.txt) is not installed correctly. Is your python version is `python=3.11.0`?

**Comment by SHYuanBest** [comment]
> Reinstalled it 5 times but still the same issue with diffusers. The requirements.txt seems to download an old version every time. pip install -r requirements.txt (with manually modified) did not work. After copy the new requirements, deleting env and install again, another error occures in egg_info (xformers) or when breaking install, modify requirements and then go on installing: Collecting xformers==0.0.28.post3 Using cached xformers-0.0.28.post3.tar.gz (7.8 MB) Preparing metadata (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [18 lines of output] Traceback (most recent call last): File "", line 2, in File "", line 34, in File "C:\pinokio\cache\TMPDIR\pip-install-mbfaevci\xformers_3c08cc2b69c74cd1bc0951c543e00ad6\setup.py", line 679, in extensions, extensions_metadata = get_extensions() File "C:\pinokio\cache\TMPDIR\pip-install-mbfaevci\xformers_3c08cc2b69c74cd1bc0951c543e00ad6\setup.py", line 445, in get_extensions cuda_version = get_cuda_version(CUDA_HOME) File "C:\pinokio\cache\TMPDIR\pip-install-mbfaevci\xformers_3c08cc2b69c74cd1bc0951c543e00ad6\setup.py", line 133, in get_cuda_version raw_output = subprocess.check_output([nvcc_bin, "-V"], universal_newlines=True) File "C:\pinokio\bin\miniconda\lib\subprocess.py", line 421, in check_output return run(*popenargs, stdout=PIPE, timeout=timeout, check=True, File "C:\pinokio\bin\miniconda\lib\subprocess.py", line 503, in run with Popen(*popenargs, **kwargs) as process: File "C:\pinokio\bin\miniconda\lib\subprocess.py", line 971, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "C:\pinokio\bin\miniconda\lib\subprocess.py", line 1456, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed

is your `torch==2.5.1`?

**Comment by SHYuanBest** [comment]
you can try uninstall `torch`, and reinstall torch via this [guide](https://pytorch.org/) for `windows`.

**Comment by DerThore** [comment]
I think I repaired my installation. I reverted following from requirements:
torch==2.3.1
torchaudio==2.3.1
torchvision==0.18.1
xformers==0.0.27
and it installed then. Now I try to render a video. No errors so far at 26%

**Comment by SHYuanBest** [comment]
cool! `torch==2.3.1` need `xformers==0.0.27`, while `torch==2.5.1` in `requirements.txt` need `xformers==0.0.28.post3`.

**Comment by DerThore** [comment]
Yes but latter one even did not work, maybe because python in pinokio is not the newest? Video at 46% without errors so far

**Comment by zishen-ucap** [comment]
> We have update [requirements.txt](https://github.com/PKU-YuanGroup/ConsisID/blob/main/requirements.txt), please reinstall the env. Or you can try `pip install git+https://github.com/SHYuanBest/ConsisID_diffusers.git`.

It seems that your work already supports diffusers. May I ask if the model parameters for diffusers are still the same as before?
